# Generated by Django 3.1 on 2020-10-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Healthdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField(max_length=50)),
                ('Dos', models.TextField()),
                ('Donts', models.TextField()),
                ('checkups', models.TextField()),
                ('Exercise', models.TextField()),
            ],
        ),
    ]
